### ISSUE TITLE
Linux Compatibility 

### ISSUE THREAD

**Issue by yapnel** [einfallstoll/ntlm-ad-client#1]
Hi

Does this work on Linux? 

Thanks

**Comment by einfallstoll** [comment]
It's pure JavaScript and should work on every OS. I only tested it on Linux though.

**Comment by yapnel** [comment]
Hi

When i tried to run the app i'm getting this error. "Error: Error: Not a valid NTLM message:"

What do i need to put into the const below?

const MESSAGE_NTLM_1 = 'MESSAGE_NTLM_1';
const MESSAGE_NTLM_3 = 'MESSAGE_NTLM_3'

Thanks.

**Comment by einfallstoll** [comment]
Valid NTLM messages from a user/browser :-)

If you don't know how they should look lile, do yourself a favor and don't use this module. Use `express-ntlm` instead, it requires less setup and does this for you.

**Comment by yapnel** [comment]
Thank you. It works perfectly. Would it be possible to get the user first and last name and email address?

**Comment by einfallstoll** [comment]
No, you have to do it yourself. See einfallstoll/express-ntlm#14
